language: cpp

matrix:

  include:

  - os: windows
    before_install:
    - dir C:/Program\ Files\ \(x86\)/Windows\ Kits/10/bin/10.0.17134.0/x64
    - cmd.exe /C 'cd && "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat"
      x86 && cd && cd "C:/Users/travis/build/varnholt/deceptus" && dir'
    - cmd.exe /C 'cd && "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat"
      x86 && cd "C:\Users\travis\build\varnholt\deceptus" && cd && "tools\qmake\qmake.exe" jumpnrun.pro
      && nmake'